### ISSUE TITLE
Failed to set default gateway

### ISSUE THREAD

**Issue by petterreinholdtsen** [sr99622/libonvif#14]
I tried unsuccessfully to set the default gateway on several cameras.  The setting would not stick.  No error appeared anywhere, but the setting where back to its old value when I restarted the Qt client to check the current settings.

I notice https://github.com/VladislavNikolin/libonvif/commit/e1e07b42b3063b72e75613dcf6385d0dffea9541 contain a commit with comment "fix SetNetworkInterfaces method".  Could there be a bug in the network setting code?

**Comment by sr99622** [comment]
First of all, let me express my thanks for your efforts to improve libonvif.  It has been very helpful to have your feedback finding issues that otherwise may have been missed.

Regarding this issue, I think this is an example of a common situation with onvif cameras.  Often the camera does not comply strictly with the protocol and in some cases will produce unexpected results or may use some modified version of the protocol.  The network settings seem to be an area where there is a lot of this type of thing happening.

Most cameras come out of China, and most of those are made by either Hikvision or Dahua.  Many brands of camera are sourced from these manufacturers, and most of the resellers will use most of the software developed by the manufacturer.  So that is to say most brands sourced by Hikvision software will respond in a similar way, likewise for Dahua.

Having said all that, some resellers do deviate from the standards and introduce quirks into the onvif interface.  An example I have just tested is from Amcrest, which is derived from Dahua.  The interface is similar, however, Amcrest does not properly respond to the DHCP commands from onvif.  The Amcrest camera will appear to have accepted the DHCP setting from the onvif command and subsequent reply, but internally, the actual DHCP setting has not changed.  This can be observed directly by using the native web app supplied by the manufacturer.  

A Dahua branded camera will respond correctly to the onvif command.  Likewise, the Hikvision derived cameras I have been able to test will respond correctly as well.  I do have a few off brand cameras that may or may not work properly with onvif network commands.

Keep in mind that the cameras I use for testing are vintage 2018 and things have probably changed since then.  I could pontificate at length regarding the nuances in the variations between cameras with respect to onvif, but I think the bottom line is that onvif is more of a suggestion than a standard, and the particulars of a camera interface implementation will dictate the level of success experienced when using onvif.  The code used by https://github.com/VladislavNikolin/libonvif/commit/e1e07b42b3063b72e75613dcf6385d0dffea9541 may very well work with a particular camera, or not with others, it is hard to tell.

My personal opinion regarding the network interface is that the system should always use the DHCP protocol and that the cameras should be on an isolated subnet without internet access so that they are not able to phone home or be subject to attacks from outside.  Perhaps, with all this in mind, it would better to just have the network tab as read only?

**Comment by petterreinholdtsen** [comment]
[sr99622]
> My personal opinion regarding the network interface is that the system
> should always use the DHCP protocol and that the cameras should be on
> an isolated subnet without internet access so that they are not able
> to phone home or be subject to attacks from outside.  Perhaps, with
> all this in mind, it would better to just have the network tab as read
> only?

Well, for the setup I have looked at, I do not have access to the DHCP
server and the only way I can locate the cameras and be sure they stay
at the same IP address across power cycles is to use a fixed IP
address.  DHCP is not an option.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by sr99622** [comment]
Looking at the code in https://github.com/VladislavNikolin/libonvif/commit/e1e07b42b3063b72e75613dcf6385d0dffea9541 it looks like the VladislavNikolin adaptation is using different xml naming convention depending on whether DHCP is enabled.  A change like this would not necessarily affect the onvif spec itself, more of an xml thing.  I'm not sure why this would be necessary. I did look through the recent onvif release notes and did not see anything regarding changes to the network interface settings. 
 
As far as I can tell, my implementation is correct.  However, due to differences between cameras as noted above, it is difficult to build a definitive consensus among a variety of cameras due to the lack of adherence to the onvif specification.

I did find another camera to test, a REOLINK model, which is a Dahua variant, and it always shows DCHP disabled through the onvif interface regardless of whether or not it is enabled in reality, so another example of non-compliance.   Using the Onvif Device Manager application produced similar results.  Further testing confirmed proper operation for Hikvision and Dahua branded cameras.

**Comment by sr99622** [comment]
After further investigation, it is learned that Dahua brand cameras do not respond to the gateway command from libonvif, nor the DNS.  Hikvision does respond to these commands.  Dahua will accept the DHCP setting from libonvif, and will accept a manually entered ip address.
