### ISSUE TITLE
Should not print passwords to stdout or log passwords in any way

### ISSUE THREAD

**Issue by petterreinholdtsen** [sr99622/libonvif#41]
When running onvif-gui and selecting a camera, the string 'Reader opening rtsp://username:password@192.168.225.75:80/0' is printed to stdout.  Printing passwords in clear text like this is a very bad idea, and I strongly recommend to mask it from such output.

**Comment by sr99622** [comment]
The code that shows the password at the prompt has been removed.  The dev branch has this change.

Be aware that this type of connection to cameras does put the username and password in clear text over the wire in the network message.  This is a feature of the rtsp protocol when used in this mode.  The underlying ffmpeg library is limited to use only this mode of the protocol.  

In order to transmit username and password over the wire as encoded tokens, the User-agent mode of the rtsp protocol should be used. The most popular library which is able to use this mode, and the one I am most familiar with is Live555.  This is what was used in vlc.  Unfortunately, Live555 has been removed from the debian package because of licensing and maintenance issues.
