### ISSUE TITLE
Is it possible to include .ui files? 

### ISSUE THREAD

**Issue by clcomputervision** [sr99622/libonvif#62]
Hello,

This work is very interesting. I have been using it for my Onvif cameras.
But is there anyway to include the UI files (.ui)? I took a look at the repo, there were only .py files.
Since I need to make some changes in UI for testing, it will be helpful to have your .ui files included.

Thank you so much.

**Comment by sr99622** [comment]
Thank you for your inquiry, your interest in the project is greatly appreciated.

The GUI for the project was developed without using .ui files.  This is partly due to a development philosophy that there be a minimum of dependencies on external code or tools for the project.  My own personal opinion is that these sorts of devices often result in unnecessary complexity when integrated into a larger context.

Having said that, one of the major goals of this project is that it be reasonably straight forward for third parties to develop applications using this project as a framework.   However, I can appreciate that some developers prefer to use the .ui format for developing GUI as it can make design and layout less cumbersome.  The result is a tradeoff between competing objectives, and in this case, .ui has been left out.

My hope is that the design patterns are clear enough that somebody could extend the code for customization without too much hair pulling.  If there is something specific that you have in mind, please let me know, I am happy to assist in getting started.  

Best Regards,

Stephen
