### ISSUE TITLE
ovif-gui not able to play the video

### ISSUE THREAD

**Issue by rouceto1** [sr99622/libonvif#73]
When I run onvif-gui (build from source or downloaded from pip) it works well until i press the play button on any camera. 
Also happens on double-click on camera.
It crashes on:
```
Traceback (most recent call last):
  File "/home/robot/git/myenv/lib/python3.8/site-packages/gui/panels/camerapanel.py", line 314, in btnStopClicked
    self.mw.playMedia(self.getStreamURI(onvif_data))
  File "/home/robot/git/myenv/lib/python3.8/site-packages/gui/main.py", line 260, in playMedia
    self.player = avio.Player()
AttributeError: module 'avio' has no attribute 'Player'
Aborted (core dumped)
```
When i import avio in standalone python it also does not find attribute Player. 

Running Ubuntu 20 LTS, on intel NUC. 
The onvif runs on a different pc and Im using X forwarding over ssh.

**Comment by rouceto1** [comment]
Same behaviour even if run natively without ssh.

**Comment by sr99622** [comment]
If I have to guess what is happening it would be that supporting packages may be missing on the machine.  It is necessary on Linux to have these installed prior to building from source or running the pip installed program.  The command line for doing this is 

```
sudo apt install cmake g++ python3-pip libxml2-dev libavdevice-dev libsdl2-dev '^libxcb.*-dev' libxkbcommon-x11-dev
```

There is also a gotcha that can happen when downloading the source, that the git clone needs to be recursive in order to get the libavio source code

```
git clone --recursive https://github.com/sr99622/libonvif
```

If you have done that already, then there are other factors in play.  My advice would be to attempt using the Build From Source instructions, but add the -v flag to the pip install command to get the compiler output.  There will be messages in there that can provide more data as to what is happening.  Go to the libavio directory and run the pip install with verbose option

```
cd libonvif/libavio
pip install -v .
```

If the build succeeds, you will see a progress marker [100%] at some point in the output.  If not, there should be some error messages indicating the source of the failure.

Let me know how things work out.

**Comment by rouceto1** [comment]
I have reinstalled the avio using your suggested commands. 
I had to update pip to allow me to do so but even though the installation was supposedly successful the error is persistent. 
If no pip update is done install of pyqt6 crashes with 
` AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'`
but that is a well documented issue of the pyqt.

I have tried to run it without the virtual environment and it did not help. Running it on conda also did not help. 

Tomorrow i can try to run it on freshly installed machine since both the PCs i have been trying on have at least a year old OS. 
Also worth mentioning that onvif-util does not detect enytthing with -a but the onvig-gui does find all my cameras even-though some have the onvif on different ports.

**Comment by rouceto1** [comment]
It apperas that even on brand new Ubuntu 20. 
Aside from the need of the pip upgrade another error pops out:  
`CMake 3.17 or higher is required.  You are running version 3.16.3`
I am currently unable to update my system to 3.17+ so I will just have to live with that. 
I also tried setting the required version in cMakeLists to 3.16 and it crashes on `fatal error: SDL.h: No such file or directory`
but that might be caused by the old version of Cmake.

**Comment by rouceto1** [comment]
Maybe it would be worth it to put a requirement of newer system to the git.

**Comment by sr99622** [comment]
Thank you so much for the feedback, your efforts are greatly appreciated.  I do vaguely remember a point at which I had to increase the minimum version of cmake in order to get things working.  I don't recall the exact reason, there are a lot of pieces that need to fit together.  Ideally, it would be possible to install the system completely using pip, without the need to use the apt install and compile.  I was able to do that on windows, but it has been more difficult on linux because of the huge number of supporting files that are needed.  I'm hoping to release a new version soon that can do this.

Best Regards,

Stephen
