### ISSUE TITLE
onvif-gui not launching on Windows 11 with Python 3.10.7

### ISSUE THREAD

**Issue by mriamnobody** [sr99622/libonvif#79]
## Environment
- **OS**: Windows 11
- **Python Version**: 3.10.7

## Issue Description
I've installed `onvif-gui` following all the recommended installation steps, but when I attempt to launch the GUI, nothing happens. No error messages are displayed, and there is no feedback in the command prompt to indicate what might be going wrong.

## Steps to Reproduce
1. Ensure Python 3.10.7 is installed and set as the default Python version.
2. Followed the installation guide for `onvif-gui`.
3. Ran the necessary commands to start the GUI as per the documentation.

## Expected Behavior
I expected the `onvif-gui` application window to open, allowing me to interact with the software.

## Actual Behavior
After running the command to start `onvif-gui`, nothing happens. There's no error output in the console, and no GUI window appears.

## Attempts to Resolve
- Checked Python version to confirm it's 3.10.7.
- Reinstalled `onvif-gui` to ensure all dependencies are correctly installed.
- Searched for similar issues in the GitHub issues section, but no similar issues was found.

## Additional Context
- There were no installation errors or warnings that appeared during setup.
- I have other Python GUI applications that are running without issue on this system.

**Comment by sr99622** [comment]
Hello,

Thank you so much for your efforts, I was not aware of this issue.

The installation has been revised and should work now as expected.  I would recommend deleting the old virtual environment and purging the pip cache and starting from scratch to get a good install.  The virtual environment you created for the install can be removed by deleting that folder using the windows folder explorer.  To delete the pip cache, use the command `pip cache purge`.

Following the directions from a fresh start should now work.  My apologies for the issues, I think there was at one time a bad version of PyQt6 that affected the linux install, so I tried to program around that by forcing the PyQt6 version, and there was an unnoticed new problem created for the windows install as a result.  These issues appear to have been fixed in the current PyQt6 version.

It is unfortunate that windows does not display the console when launching using these methods.  In the future, if you have unusual problems on windows, you can run the program from a standard python console.  Download the source distribution and go to the libonvif/onvif-gui directory and type `python run.py`, which will run the program with console messages.

Thank you again for your help, it is difficult to observe all the permutations of the program operation due to limited resources, so feedback like this is greatly appreciated.

Best Regards,

Stephen

**Comment by mriamnobody** [comment]
Thanks a lot @sr99622. It works now.
