### ISSUE TITLE
Error on Ubuntu 20.04.6 LTS (Both installation and build from source)

### ISSUE THREAD

**Issue by kanishkasw** [sr99622/libonvif#90]
Hi, Im getting the following error when trying to run on Ubuntu 20  while following the instructions in the Readme

$ onvif-gui 
Traceback (most recent call last):
  File "/home/user/Personal/Tryout/libonvif/onvif-gui/myvenv/bin/onvif-gui", line 5, in <module>
    from gui.main import run
  File "/home/user/Personal/Tryout/libonvif/onvif-gui/myvenv/lib/python3.10/site-packages/gui/__init__.py", line 1, in <module>
    from .main import MainWindow
  File "/home/user/Personal/Tryout/libonvif/onvif-gui/myvenv/lib/python3.10/site-packages/gui/main.py", line 42, in <module>
    from gui.panels import CameraPanel, FilePanel, SettingsPanel, VideoPanel, AudioPanel
  File "/home/user/Personal/Tryout/libonvif/onvif-gui/myvenv/lib/python3.10/site-packages/gui/panels/__init__.py", line 1, in <module>
    from .camerapanel import CameraPanel
  File "/home/user/Personal/Tryout/libonvif/onvif-gui/myvenv/lib/python3.10/site-packages/gui/panels/camerapanel.py", line 26, in <module>
    from gui.onvif import NetworkTab, ImageTab, VideoTab, PTZTab, SystemTab, LoginDialog, \
  File "/home/user/Personal/Tryout/libonvif/onvif-gui/myvenv/lib/python3.10/site-packages/gui/onvif/__init__.py", line 7, in <module>
    from .datastructures import Session, StreamState, MediaSource, Camera
  File "/home/user/Personal/Tryout/libonvif/onvif-gui/myvenv/lib/python3.10/site-packages/gui/onvif/datastructures.py", line 41, in <module>
    class Session(onvif.Session):
AttributeError: module 'libonvif' has no attribute 'Session'

**Comment by sr99622** [comment]
Hello, thank you so much for reaching out. It would appear from the error message that libonvif has failed to compile. In most cases, this is due to a dependency problem, either not installed or some kind of version mismatch. The dependency in this case would be libxml2. You can verify installation using the command
```
apt list --installed | grep libxml2
```
You should get a response showing the version installed. If there is a good libxml2 installed, navigate to the libonvif root directory and use the command
```
assets/scripts/compile
```
There will be a long output that shows the internal messages generated by the compiler. Near the top should be a section showing the output of the libonvif compile. If there has been a failure, the error message will show specifics. 

Please let me know what those messages are, and I can have a better idea of what to do to fix the install.

**Comment by kanishkasw** [comment]
Hi Thanks for the quick response @sr99622!. 
libxml2 version
> $ apt list --installed | grep libxml2
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> libxml2-dev/focal,now 2.9.14+dfsg-0.1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed]
> libxml2/focal,now 2.9.14+dfsg-0.1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed,automatic]

I was able to fix some issues by looking at assets/scripts/compile output. Still unable to fix the following though

> CMake Generate step failed.  Build files cannot be regenerated correctly.
>   Scanning dependencies of target avio
>   [  7%] Building CXX object CMakeFiles/avio.dir/src/avio.cpp.o
>   In file included from /home/kanishkasw/Personal/Tryout/libonvif/libavio/include/Player.h:29,
>                    from /home/kanishkasw/Personal/Tryout/libonvif/libavio/include/avio.h:31,
>                    from /home/kanishkasw/Personal/Tryout/libonvif/libavio/src/avio.cpp:23:
>   /home/kanishkasw/Personal/Tryout/libonvif/libavio/include/Display.h:25:10: fatal error: SDL.h: No such file or directory
>      25 | #include <SDL.h>
>         |          ^~~~~~~
>   compilation terminated.
>   make[2]: *** [CMakeFiles/avio.dir/build.make:83: CMakeFiles/avio.dir/src/avio.cpp.o] Error 1
>   make[1]: *** [CMakeFiles/Makefile2:116: CMakeFiles/avio.dir/all] Error 2
>   make: *** [Makefile:104: all] Error 2

**Comment by sr99622** [comment]
Thank you for the feedback, your input is greatly appreciated. The current issue with the SDL.h is similar to what was experienced with libxml2. I'm wondering if maybe a step was missed during the installation. 

```
sudo apt install cmake g++ git python3-pip virtualenv libxml2-dev libavdevice-dev libsdl2-dev '^libxcb.*-dev' libxkbcommon-x11-dev
```

This is where the dependencies are installed prior to compilation. It's not my favorite way to do this, but managing these packages is very difficult due to their large and complex nature, so we rely on the Operating System utilities (apt) to handle the job. It is safe to run this command even if the packages are already installed, so there is no harm in trying. To be honest, I have not yet back tested Ubuntu 20.04, so it is possible there are some issues with that particular OS.  I will be running that test later today to verify.

I'm hoping that running the command shown above will clear up the errors you are having. In the meantime, I will test test the 20.04 version install. Please let me know if you are experiencing further issues.

Best Regards,

Stephen
